<audio title="09_(...x)：不是表达式、语句、函数，但它却能执行" src="https://static001.geekbang.org/resource/audio/e4/65/e4d105b8e77cf7ff7010baf1ced35465.mp3" controls="controls"></audio> 
<p>你好，我是周爱民，欢迎回到我的专栏。</p><p>从之前的课程中，你应该已经对语句执行和函数执行有了基本的了解。事实上，这两种执行其实都是对<strong>顺序</strong>、<strong>分支</strong>与<strong>循环</strong>三种逻辑在语义上的表达。</p><p>也就是说，不论一门语言的语法有什么特异之处，它对“执行逻辑”都可以归纳到这三种语义的表达方式上来。这种说法事实上也并不特别严谨，因为这三种基本逻辑还存在进一步抽象的空间（这些也会是我将来会讨论到的内容，今天暂且不论）。</p><p>今天这一讲中，主要讨论的是第二种执行的一些细节，也就是对“函数执行”的进一步补充。</p><p>在上一讲中，我有意将函数分成三个语义组件来讲述。我相信在绝大多数的情况下，或者在绝大多数的语言教学中，都是不必要这样做的。这三个语义组件分别是指参数、执行体和结果，将它们分开来讨论，最主要的价值就在于：<span class="orange">通过改造这三个语义组件的不同部分，我们可以得到不同的“函数式的”执行特征与效果。</span>换而言之，可以通过更显式的、特指的或与应用概念更贴合的语法来表达新的语义。与所谓“特殊可执行结构”一样，这些语义也用于映射某种固定的、确定的逻辑。</p><p>语言的设计，本质就是为确定的语义赋以恰当的语法表达。</p><h2>递归与迭代</h2><p>如果循环是一种确定的语义，那么如何在函数执行中为它设计合适的语法表达呢？</p><!-- [[[read_end]]] --><p>递归绝对是一个好的、经典的求解思路。递归将循环的次数直接映射成函数“执行体”的重复次数，将循环条件放在函数的参数界面中，并通过函数调用过程中的值运算来传递循环次数之间的数值变化。递归作为语义概念简单而自然，唯一与函数执行存在（潜在的）冲突的只是所谓栈的回收问题，亦即是尾递归的处理技巧等，但这些都是实现层面的要求，而与语言设计无关。</p><p>由于递归并不改变函数的三个语义组件中的任何一个，因此它与函数执行过程完全没有冲突，也没有任何新的需求与设计。这句话的潜在意思是说，函数的三个语义组件都不需要为此作出任何的设计修改，例如：</p><pre><code>const f = x =&gt; x &amp;&amp; f(--x);
</code></pre><p>在这段代码中，是没有出现任何特殊的语法和运算/操作符的，它只是对函数、（变量或常量的）声明、表达式以及函数调用等等的简单组合。</p><p>然而迭代不是。迭代也是循环语义的一种实现，它说明循环是“函数体”的重复执行，而不是“递归”所理解的“函数调用自己”的语义。这是一种可受用户代码控制的循环体。你可以尝试创建这样一个简单的迭代函数：</p><pre><code>// 迭代函数
function foo(x = 5) {
  return {
    next: () =&gt; {
      return {done: !x, value: x &amp;&amp; x--};
    }
  }
}
</code></pre><p>然而请仔细观察这样的两个实现，你需要注意在这个迭代函数中有“值(value)和状态(done)”两个控制变量，并且它的实际执行代码与上面的函数f()是一样的：</p><pre><code>// in 函数f()
x &amp;&amp; f(--x)

// in 迭代foo()
x &amp;&amp; x--
</code></pre><p>也就是说，递归函数“<em>f()</em>”和迭代函数“foo()”其实是在实现相同的过程。只是由于“递归完成与循环过程的结束”在这里是相同的语义，因此函数“<em>f()</em>”中不需要像迭代函数那样来处理“状态(done)”的传出。递归函数“<em>f()</em>”，要么结束，要么无穷递归。</p><h2>迭代对执行过程的重造和使用</h2><p>在JavaScript中，是通过一个中间对象来使用迭代过程_foo()_的。该中间对象称为迭代器，foo()称为迭代器函数，用于返回该迭代器。例如：</p><pre><code>var tor = foo(); // default `x` is 5
...
</code></pre><p>迭代器具有<code>.next()</code>方法用于一次（或每次）迭代调用。由于没有约定迭代调用的方式，因此可以用任何过程来调用它。例如：</p><pre><code>// 在循环语句中处理迭代调用
var tor = foo(5), result = tor.next();
while (!result.done) {
  console.log(result.value);
  result = tor.next();
}
</code></pre><p>除了一些简单的、概念名词上的置换外，这些与你所见过的绝大多数有关“迭代器与生成器”的介绍并没有什么不同。并且你也应当理解，正是这个“.next()”调用的界面维护了迭代过程的上下文，以及值之间的相关性（例如一个值序列的连续性）。</p><p>根据约定，如果有一个对象“包含”这样一个迭代器函数（以返回一个迭代器），那么这个对象就是可迭代的。基于JavaScript中“对象是属性集（所以所有包含的东西都必然是属性）”的概念，这个迭代函数被设计为称为“Symbol.iterator”的符号属性。例如：</p><pre><code>let x = new Object;
x[Symbol.iterator] = foo; // default `x` is 5
</code></pre><p>现在，你可以使用这个可迭代对象了：</p><pre><code>&gt; console.log(...x);
5 4 3 2 1
</code></pre><p>现在，你看到了这一讲标题中的代码：</p><pre><code>(...x)
</code></pre><p>不过，不同的是，标题中的代码是不能执行的。</p><h2>展开语法</h2><p>问题的关键点在于：<code>...x</code>是什么？</p><p>在形式上，“…”看起来像是一个运算符，而<code>x</code>是它的操作数。但是，如果稍微深入地问一下这个问题，就会令人生疑了。例如：如果它是运算符，那么运算的返回值是什么？</p><p>答案是，它既不返回值，也不返回引用。</p><p>那么如果它不是运算符，或者说<code>...x</code>也并不是表达式，或许它们可以被理解为“语句”吗？即使如此，与上面相同的问题也会存在。例如：如果它是语句，那么该语句的返回值是什么？</p><p>答案是，既不是空（Empty），也不是其它结果（Result）。因此它也不是语句（并且，因为console.log()是表达式，而表达式显然也“不可能包含语句”）。</p><p>所以，<code>...x</code>既不是表达式，也不是语句。它不是我们之前讲过的任何一种概念，而仅仅只是“语法”。作为语法，ECMAScript在这里规定它只是对一个确定的语义的封装。</p><p>在语义上，它用于“展开一个可迭代对象”。</p><h2>如何做到呢？</h2><p>为什么我要绕这么大个圈子来介绍这个“简单的”展开语法呢？又或者说，ECMAScript为什么要弄出这么一个“新”概念呢？</p><p>这与函数的第三个语义组件——“值”是有关的。在JavaScript中（也包括在绝大多数支持函数的语言中），函数只能返回一个值。然而，如果迭代器表达的是一个重复执行的执行体，并且每次执行都返回一个值，那么又怎么可能用“返回一个值”的函数来返回呢？</p><p>与此类似，语句也只有一个这样的单值返回，所以批语句执行也仍然只是返回最后一行的结果。并且，一旦<code>...x</code>被理解为语句，那么它就不能用作操作数，成为一个表达式的部分。这在概念上是不容许的。所以，当在“函数”这个级别表达多次调用时，尽管它可以通过“对象（迭代对象）”来做形式上的封装，却无法有效地表达“多次调用的多个结果”。这才是展开语法被设计出来的原因。</p><p>如果可迭代对象表达的是“多个值”，那么可以作用于它的操作或运算通常应该是那些面向“值的集合（Collections）”的。更确切地说，它是可以面向“索引集合（Indexed Collections）”和“键值集合（Keyed Collections）”设计的语法概念。因此在现在的，以及将来的ECMAScript规范中，你将会看到它的操作，例如通常包括的合并、映射、筛选等等，将在包括对象、数组、集（Set）、图（Map）等等数据的处理中大放异彩。</p><p>而现在，其实我想问的问题是，在函数中是如何做到迭代处理的呢？</p><h2>内部迭代过程</h2><p>迭代的本质是多次函数调用，在JavaScript内部实现这一机制，本质上就是管理这些多次调用之间的关系。这显然包括一个循环过程，和至少一个循环控制变量。</p><p>这个迭代有一个开启过程，简单的如展开语法（“…”），复杂的如for…of语句。这些语法/语法结构通过类似如下两个步骤来完成迭代的开启：</p><pre><code>var tor = foo(5), result = tor.next();
while (!result.done) ...
</code></pre><p>但是如同我在之前的课程，以及上面的讨论中一再强调的这是“一个执行过程”，既然是过程，那么就存在过程被中断的可能。简单的示例如下：</p><pre><code>while (!result.done) {
  break;
}
</code></pre><p>是的，这个过程什么也不会发生。如果是在经典的while循环里面，那么它的result和tor，以及foo()调用所开启的那个函数闭包都被当前上下文管理或回收。然而，如果在一个展开过程，或者for…of循环中，相应的“语法”管理上述这些组件的时候又需要怎样的处理呢？例如：</p><pre><code>function touch(x) {
  if (x==2) throw new Error(&quot;hard break&quot;);
}

// 迭代函数
function foo2(x = 5) {
  return {
    next: () =&gt; {
      touch(x); // some process methods
      return {done: !x, value: x &amp;&amp; x--};
    }
  }
}

// 示例
let x = new Object;
x[Symbol.iterator] = foo2; // default `x` is 
</code></pre><p>测试如下：</p><pre><code>&gt; console.log(...x);
Error: hard break
</code></pre><p>这个示例是一个简单异常，但如果这个异常发生于for…of中：</p><pre><code>&gt; for (let i of x) console.log(i);
5
4
3
Error: hard break
</code></pre><p>在这两种示例中，异常都是发生于foo2()这个函数调用的一个外部处理过程中，而等到用户代码有机会操作时，已经处于console.log()调用或for…of循环中了，如果用户在这里设计异常处理过程，那么foo2()中的touch(x)管理和涉及的资源都无法处理。因此，ECMAScript设计了另外两个方法来确保foo2()中的代码在“多次调用”中仍然是受控的。这包括两个回调方法：</p><blockquote>
<p>tor.return()，当迭代正常过程退出时回调<br>
tor.throw()，当迭代过程异常退出时回调</p>
</blockquote><p>这并不难于证实：</p><pre><code>&gt; Object.getOwnPropertyNames(tor.constructor.prototype)
[ 'constructor', 'next', 'return', 'throw' ]
</code></pre><p>现在如果给tor的return属性加一个回调函数，会发生什么呢？</p><pre><code>// 迭代函数
function foo2(x = 5) {
  return {
    // 每次.next()都不会返回done状态，因此可列举无穷次
    &quot;next&quot;: () =&gt; new Object,  // result instance, etc.
    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;)
  }
}
let x = new Object;
x[Symbol.iterator] = foo2; // default `x` is 5
</code></pre><p>测试一下：</p><pre><code># 列举x，第一次迭代后即执行break;
&gt; for (let i of x) break;
RETURN!
</code></pre><p>结果是<code>RETURN!</code>？</p><p>什么鬼？！</p><h2>异常处理</h2><p>并且如果你试图在tor.throw中去响应foo()迭代中的异常，却什么也得不到。例如：</p><pre><code>// 迭代函数
function foo3(x = 5) {
  return {
    // 第一个.next()执行时即发生异常
    &quot;next&quot;: () =&gt; { throw new Error },
    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)
  }
}
let x = new Object;
x[Symbol.iterator] = foo3;
</code></pre><p>在测试中，异常直接被抛给了全局：</p><pre><code>&gt; console.log(...x);
Error
    at Object.next (repl:4:27)
</code></pre><p>继续！显然可以把这个例子跟最开始使用的foo()组合起来，foo()迭代可以正确地得到<code>5 4 3 2 1</code>，而上面的return/throw可以捕获过程的退出或异常。例如：</p><pre><code>// 迭代函数
function foo4(x = 5) {
  return {
    // foo()中的next
    next: () =&gt; {
      return {done: !x, value: x &amp;&amp; x--};
    },


    // foo2()和foo3()中的return和throw
    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),
    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)
  }
}


let x = new Object;
x[Symbol.iterator] = foo4
</code></pre><p>测试：</p><pre><code>&gt;&gt;console.log(...x);
5 4 3 2 1
</code></pre><p>Ok，成功是成功了！但是，“RETURN/THROW“呢？</p><p>这里简直就是迭代的地狱！</p><h2>是谁的退出与异常？</h2><p>回顾之前的内容，迭代过程并不是一个语法执行的过程，而是应该理解为一组函数执行的过程；对于这一批函数执行过程中的结束行为，也应该理解为函数内的异常或退出。因此，尽管在for…of的表面上看，是break发生了语句中的中止，而在迭代处理的内部发生的，却是“一个迭代过程的退出”。与此同样复杂的是，在这一批函数的多个执行上下文中，不论是在哪儿发生了异常，其实只有外层的第一个能捕获异常的环境能响应这个异常。</p><p>简单地说：“退出(RETURN)”是执行过程的，“异常(THROW)”是外部的。</p><p>JavaScript中，迭代被处理为两个实现用的组件，一个是（循环的）迭代过程，另一个是（循环的）迭代控制变量。表现在tor这个迭代对象上来看，就是（对于循环来说，）“如果谁使用迭代变量tor，那么就是谁管理迭代过程”。</p><p>这个“管理循环过程”意味着：</p><ul>
<li>如果迭代结束（不论它因为什么结束），那么触发tor.return事件；</li>
<li>如果发现异常（只要是当前环境能捕获到的异常），那么触发tor.throw事件。</li>
</ul><p>这两个过程总是发生在“管理循环过程”的行为框架中。例如在下面这个过程中：</p><pre><code>for (let i of x) {
  if (i == 2) break;
}
</code></pre><p>由于 <code>for .. of</code>语句将获得x对象的迭代变量tor，那么它也将管理x对象的迭代过程。因此，在for语句break之后（在for语句将会退出自己的作用之前），它也就必须去“通知”x对象迭代过程也结束了，于是这个语句触发了tor.return事件。</p><p>同样，如果是一个数组展开过程：</p><pre><code>console.log(...x);
</code></pre><p>那么将是<code>...x</code>这个“展开语法”来负责上述的迭代过程的管理和“通知”，这个语法在它所在的位置上是无法响应异常的。该语法所在位置是一个表达式，不可能在它内部使用<code>try..catch</code>语句。</p><pre><code>function touch(x) {
  if (x==2) throw new Error(&quot;hard break&quot;);
}

// 迭代函数
function foo5(x = 5) {
  return {
    // foo2()中的next
    next: () =&gt; {
      touch(x); // some process methods
      return {done: !x, value: x &amp;&amp; x--};
    },

    // foo3()中的return和throw
    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),
    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)
  }
}

let x = new Object;
x[Symbol.iterator] = foo5;

try {
  console.log(...x); 
}
catch(e) {} // m
</code></pre><p>这段示例代码将mute掉一切：既没有console.log()输出，也没有异常信息，tor的return/throw一个也没有发生。</p><p>对于x这个可迭代对象，以及foo5()这个迭代器函数来说，世界是安静的：它既不知道自己发生了什么，也不知道它的外部世界发生了什么。因为<code>...x</code>这个语法既没有管理迭代过程（因此不理解tor的退出/return行为），也没有在异常发生时向内“通知”tor.throw事件的能力。</p><h2>知识回顾</h2><p>标题中的示例是不能执行的，因为其中的括号并不是表达式中分组运算符，也不是语句中的函数调用，也不是声明中的形式参数表。声明中的<code>...x</code>被定义为“展开语法”，是逻辑的映射（它返回的是处理逻辑），而不是“值”或“引用”。它在不同的位置被JavaScript解释成不同的语义，包括对象展开和数组展开，并通过一组特定的代码来实现上述的语义。</p><p>在<code>...x</code>被理解为数组展开时，本质上是将<code>x</code>视为一个可迭代对象，并通过一个迭代变量（例如tor）来管理它的迭代过程。在JavaScript中的迭代对象x的生存周期是交由使用它的表达式、语句或语法来管理的，包括在必要的时候通过tor来向内通知return/throw事件。</p><p>在本讲的示例中，展开语法“…x”是没有向内通知的能力的，而“for … of”可以隐式地向内通知。对于后者，for…of中的break和continue，以及循环的正常退出都能够通知return事件，但它并没有内向通知throw的能力，因为for…of语句本身并不捕获和处理throw。</p><h2>思考题</h2><ul>
<li>既然上面的过程完全不使用tor.throw，那么它被设计出来做什么？</li>
<li><code>...x</code>为什么称为“展开语法”，为什么ECMAScript不提供一个表达式/语句之外的概念来指代它？</li>
<li>continue在那种情况下触发tor.return？</li>
<li>yield* x将导致什么？</li>
</ul><p>欢迎你在进行深入思考后，与其他同学分享自己的想法，也让我有机会能听听你的收获。</p>
<style>
    ul {
      list-style: none;
      display: block;
      list-style-type: disc;
      margin-block-start: 1em;
      margin-block-end: 1em;
      margin-inline-start: 0px;
      margin-inline-end: 0px;
      padding-inline-start: 40px;
    }
    li {
      display: list-item;
      text-align: -webkit-match-parent;
    }
    ._2sjJGcOH_0 {
      list-style-position: inside;
      width: 100%;
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      margin-top: 26px;
      border-bottom: 1px solid rgba(233,233,233,0.6);
    }
    ._2sjJGcOH_0 ._3FLYR4bF_0 {
      width: 34px;
      height: 34px;
      -ms-flex-negative: 0;
      flex-shrink: 0;
      border-radius: 50%;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 {
      margin-left: 0.5rem;
      -webkit-box-flex: 1;
      -ms-flex-positive: 1;
      flex-grow: 1;
      padding-bottom: 20px;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 ._2zFoi7sd_0 {
      font-size: 16px;
      color: #3d464d;
      font-weight: 500;
      -webkit-font-smoothing: antialiased;
      line-height: 34px;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 ._2_QraFYR_0 {
      margin-top: 12px;
      color: #505050;
      -webkit-font-smoothing: antialiased;
      font-size: 14px;
      font-weight: 400;
      white-space: normal;
      word-break: break-all;
      line-height: 24px;
    }
    ._2sjJGcOH_0 ._10o3OAxT_0 {
      margin-top: 18px;
      border-radius: 4px;
      background-color: #f6f7fb;
    }
    ._2sjJGcOH_0 ._3klNVc4Z_0 {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      -webkit-box-pack: justify;
      -ms-flex-pack: justify;
      justify-content: space-between;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      margin-top: 15px;
    }
    ._2sjJGcOH_0 ._10o3OAxT_0 ._3KxQPN3V_0 {
      color: #505050;
      -webkit-font-smoothing: antialiased;
      font-size: 14px;
      font-weight: 400;
      white-space: normal;
      word-break: break-word;
      padding: 20px 20px 20px 24px;
    }
    ._2sjJGcOH_0 ._3klNVc4Z_0 {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      -webkit-box-pack: justify;
      -ms-flex-pack: justify;
      justify-content: space-between;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      margin-top: 15px;
    }
    ._2sjJGcOH_0 ._3Hkula0k_0 {
      color: #b2b2b2;
      font-size: 14px;
    }
</style><ul><li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/15/1f/86/3a7eeac4.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>leslee</span>
  </div>
  <div class="_2_QraFYR_0">1. 他可以手动调用..., 在you dont know js 里面说过这个 .throw 可以委托异常.<br>2. 这是由他的语义决定的, 如果他是一个语句, 那他就不能跟表达式连用, 如果他是一个表达式, 那他的返回值又显得有点多余.<br>3. <br>```js<br>function foo4(x = 5) {<br>      return {<br>        next: () =&gt; {<br>          return { done: !x, value: x &amp;&amp; x-- };<br>        },<br>        &quot;return&quot;: () =&gt; {<br>          return { done: true, value: &#39;恭喜发财&#39; }<br>        },<br>        &quot;throw&quot;: () =&gt; {<br>          console.log(&quot;THROW!&quot;)<br>        }<br>      }<br>    }<br><br><br>    let x = new Object;<br>    x[Symbol.iterator] = foo4<br>aaa: for (let item of x) {<br>      console.log(item, &#39;w&#39;)<br>      for (let item of x) {<br>        console.log(item, &#39;i&#39;)<br>        continue aaa;<br>      }<br>    }<br>&#47;&#47;  echo &#39;return&#39; x2<br>&#47;&#47; 当return 函数返回undefined 的时候会报这个错 Iterator result undefined is not an object<br>```<br>被我试出来了, 当return函数返回undefined , 且嵌套循环且continue带有外层循环语句的标签的时候, 他会触发两次return, 缺一个条件都不行. 当return函数返回一个正常的迭代器对象`{done:true, value: &#39;xxx&#39;}`, 他会输出5个return, 这个return应该由内层的forof 发出, 因为内层的循环直接被打断了, 继续下去的是外层循环, 单层循环不行是因为 continue 的语义并不是打断&#47;结束, 是这样理解么老师, 这里面还有其他的豆子么,老师.<br>4. 把x展开, 返回迭代值 , 如果 没有 * 返回的将是迭代器函数, .</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 关于1和3，老实说，这个东西确实灰常灰常麻烦，你得自己去体会tor.return和tor.throw的含义与用法。<br><br>我只能提示说：谁创建了tor，那么就该是谁去调用tor.return和tor.throw。这两个方法不是事件触发，而是“tor的持有者”调用。<br><br>关于2，你的答案没有对或不对的问题，但我觉得还有深思的余地。不妨多思考一下，不着急有结论。另外，这个问题没有标准答案。<br><br>关于4，你“可能”是对的，但似乎表达得不太清楚。^^.</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-12-26 21:57:49</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/11/a3/ea/53333dd5.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>HoSalt</span>
  </div>
  <div class="_2_QraFYR_0">老师，为什么fn(...args)怎么变成了一个个的参数，而在{...args}怎么变成了对象属性的一部分，这是谁控制的？</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: ...x 这个称为“展开语法”，是在语法分析阶段就被替换成了硬代码的。所以简单的说，在执行期的时候就是一个循环&#47;迭代处理，并且根据上下文的不同，来决定是展开成参数，还是属性。<br><br>类似于用字符串替换重写了代码，硬写入的。^^.</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-05-18 09:08:44</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/0f/78/51/4790e13e.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Smallfly</span>
  </div>
  <div class="_2_QraFYR_0"><br>&#47;&#47; 迭代函数<br>function foo(x = 5) {<br>  return {<br>    next: () =&gt; {<br>      return {done: !x, value: x &amp;&amp; x--};<br>    }<br>  }<br>}<br><br>const tor = foo();<br>const names = Object.getOwnPropertyNames(tor.constructor.prototype);<br><br>console.log(names);<br>&#47;*<br>  [ &#39;constructor&#39;,<br>  &#39;__defineGetter__&#39;,<br>  &#39;__defineSetter__&#39;,<br>  &#39;hasOwnProperty&#39;,<br>  &#39;__lookupGetter__&#39;,<br>  &#39;__lookupSetter__&#39;,<br>  &#39;isPrototypeOf&#39;,<br>  &#39;propertyIsEnumerable&#39;,<br>  &#39;toString&#39;,<br>  &#39;valueOf&#39;,<br>  &#39;__proto__&#39;,<br>  &#39;toLocaleString&#39; ]<br>*&#47;<br><br>请问老师我用 node 执行上面的代码，为什么跟文中的以下输出不一致呢。<br><br>&gt; Object.getOwnPropertyNames(tor.constructor.prototype)<br>[ &#39;constructor&#39;, &#39;next&#39;, &#39;return&#39;, &#39;throw&#39; ]<br></div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 这里的foo()是一个模拟生成器函数的界面的，所以它当然得不到“真的”生成器。<br><br>你需要的示例是这样：<br>```<br>function* foo() {}<br>tor = foo();<br>names = Object.getOwnPropertyNames(tor.constructor.prototype);<br>```</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-01-16 09:36:17</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/10/04/8d/005c2ff3.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>weineel</span>
  </div>
  <div class="_2_QraFYR_0">四个思考题，都没能找到很好的答案。。。</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-12-02 23:15:36</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src=""
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Sam</span>
  </div>
  <div class="_2_QraFYR_0">根据周老师的指点，谁创建谁调用。以下是我想到一个办法调用throw方法(不知理解是否合理)：<br>function* foo() {<br>  yield 1<br>  yield 2<br>  yield 3<br>}<br>foo.prototype.throw = function(e) {<br>  console.log(&quot;Test Error &quot; + e)<br>}<br>let tor = foo()<br>for(let item of tor) {<br>  console.log(item)<br>  tor.throw(new Error(&#39;迭代器循环休内触发&#39;))<br>}</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 看起来这样是能用的，并且事实上通常也需要这样来使用。但是，总之，在这里throw()的原则与应用都是令人困惑的。——我的意思是js语言在这里的设计原本就很令人困惑。由于篇幅， 这一讲并没有关于这个部分的更多讨论，而仅仅是开了个头。如果你有兴趣了解更深的话，建议参阅《javascript语言精髓与编程实践》的5.4.4.3和5.4.5的内容。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-08-12 10:04:48</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/22/10/e2/35f2fc23.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>吉法师</span>
  </div>
  <div class="_2_QraFYR_0">迭代感觉用不着啊……</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-04-06 15:54:07</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src=""
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>油菜</span>
  </div>
  <div class="_2_QraFYR_0">&quot;用户在这里设计异常处理过程，那么 foo2() 中的 touch(x) 管理和涉及的资源都无法处理。&quot;<br>是指在“console.log() 调用或 for…of 循环中”处理异常么？ touch(x)和涉及的资源无法处理，是什么意思呢？ 是指touch(x)内部抛出异常，但catch不到异常么？<br>-------------------------------------<br>function touch(x) {<br> try{<br>  if (x==2) throw new Error(&quot;hard break&quot;);<br>  }catch(c){<br>     console.log(&#39;c:&#39;+ c);<br>  }<br>}<br><br>&#47;&#47; 迭代函数<br>function foo2(x = 5) {<br>  return {<br>    next: () =&gt; {<br>      touch(x); &#47;&#47; some process methods<br>      return {done: !x, value: x &amp;&amp; x--};<br>    },<br>    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),<br>    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)<br>  }<br>}<br><br>&#47;&#47; 示例<br>var x = new Object;<br>x[Symbol.iterator] = foo2; &#47;&#47; default `x` is <br><br>try{<br>		console.log(...x);<br>}catch(d){<br>  console.log(&#39;d:&#39;+ d);<br>}<br><br>结果：touch(x)可以处理异常<br>c:Error: hard break   <br>5 4 3 2 1</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 以for..of语句为例，在那个例子中发生异常时，在`console.log(i)`位置是无法捕获异常的；在for..of外层可以加一层异常，但是无法处理touch()过程所分配的（或者所&quot;碰(touch)&quot;过的）资源。例如，如果touch()过程打开了一个文件，那么当异常发生时，在哪里去关闭文件呢？</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-11-13 13:26:03</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src=""
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>油菜</span>
  </div>
  <div class="_2_QraFYR_0">1 语言设计者有考虑到异常处理，但功能上还不够完善。类似写了个todo<br>2 使用者或设计者需要一种语法，能够接收所有参数。例如剩余参数 function foo(...x){console.log(x)}, 数组x可以接收所有入参。“为什么 ECMAScript 不提供一个表达式 &#47; 语句之外的概念来指代它”（老师可能是想说，之内的概念，文章标题已指出(...x)既不是表达式，也不是语句），可能是和现有的编译逻辑冲突。例如我们写程序，如果出现分支情况，最简单的做法是写个if判断，区分分支。表达式，语句，语法，可能是不同分支处理。<br><br>3 本人简单测试，以下几种都会触发tor.return。<br>for(var i of x ) {console.log(i);break};<br>for(var i of x ) {console.log(i); throw new Error(&#39;test&#39;)}<br>for(var i of x ) {console.log(i);continue};<br><br>4 只知其然，不知其所以然<br>&#47;&#47; 迭代函数<br>function foo6(x = 5) {<br>  return {<br>    &#47;&#47; foo2()中的next<br>    next: () =&gt; {<br>      return {done: !x, value: x &amp;&amp; x--};<br>    },<br>    &#47;&#47; foo3()中的return和throw<br>    &quot;return&quot;: () =&gt; console.log(&quot;RETURN!&quot;),<br>    &quot;throw&quot;: () =&gt; console.log(&quot;THROW!&quot;)<br>  }<br>}<br>var b = foo6();<br>b.next();&#47;&#47; { done: false, value: 5 }<br>b.next();&#47;&#47; { done: false, value: 4 }<br><br>&#47;&#47;yield用法<br>var x = new Object;<br>x[Symbol.iterator] = foo6;<br>function* g1() { yield* x}; <br>var a = g1();<br>a.next(); &#47;&#47; { done: false, value: 5 }<br>a.next(); &#47;&#47; { done: false, value: 4 }</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-11-13 11:03:45</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/12/d4/37/528a43e7.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Elmer</span>
  </div>
  <div class="_2_QraFYR_0">这个贴近语义的语法和解析为可执行结构的关系是什么呢</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 这个这个，你的这句话我读不太明白意思。<br><br>如果你的意思是“语法与可执行结构”的关系，那么可以简单地说：在语法解析之后，会在相应的位置上插入一段硬代码，以支持对应的可执行结构的实际语义。<br><br>例如如果是“展开...x作为参数”，那么对应的位置上的代码，其实就是把数组x添加到参数列表的指定位置。这是一段确定的逻辑。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-07-07 17:29:39</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/15/ea/74/7dd9c65e.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>亦枫丶</span>
  </div>
  <div class="_2_QraFYR_0">看了好久，对于第二个思考题恍然大悟，我想可以用文章开头的 <br><br>**“换而言之，可以通过更显式的、特指的或与应用概念更贴合的语法来表达新的语义。”**<br><br>这句话来解释吧，它只是“展开”逻辑的一种实现，叫它展开语法更为显式，与应用概念更贴合吧。</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-04-03 22:26:33</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/15/45/da/71b7599d.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>antimony</span>
  </div>
  <div class="_2_QraFYR_0">老师，请问一下这个迭代和递归的关系您是从sicp中了解到的吗？</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 不是。^^.<br><br>循环与递归的关系可能源出于SICP。但我是在读SICP之前听一个朋友谈及的，后来意识到根本问题是抽象模型内在的一致性。所以才有了《程序原本》中说“本质上相同的抽象系统，其解集的抽象本质上也是相同的”。基于此，再观察论述迭代与递归的关系，就是显而易见的事情了。<br><br>《程序原本》：<br>https:&#47;&#47;github.com&#47;aimingoo&#47;my-ebooks</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-02-09 21:12:30</div>
  </div>
</div>
</div>
</li>
</ul>